#!/bin/sh

function make_handheld(){
	inkscape -e handheld/drawable-mdpi/${3:-$1}.png -w $2 $1.svg
	inkscape -e handheld/drawable-hdpi/${3:-$1}.png -w `echo $2 1.5\*p | dc` $1.svg
	inkscape -e handheld/drawable-xhdpi/${3:-$1}.png -w `echo $2 2\*p | dc` $1.svg
	inkscape -e handheld/drawable-xxhdpi/${3:-$1}.png -w `echo $2 3\*p | dc` $1.svg
	inkscape -e handheld/drawable-xxxhdpi/${3:-$1}.png -w `echo $2 4\*p | dc` $1.svg
}

function make_wear(){
	inkscape -e wear/drawable-mdpi/${3:-$1}.png -w $2 $1.svg
	inkscape -e wear/drawable-hdpi/${3:-$1}.png -w `echo $2 1.5\*p | dc` $1.svg
	inkscape -e wear/drawable-xhdpi/${3:-$1}.png -w `echo $2 2\*p | dc` $1.svg
	inkscape -e wear/drawable-xxhdpi/${3:-$1}.png -w `echo $2 3\*p | dc` $1.svg
	inkscape -e wear/drawable-xxxhdpi/${3:-$1}.png -w `echo $2 4\*p | dc` $1.svg
}


make_handheld ic_play 50
make_handheld ic_pause 50

make_handheld ic_prev 40
make_handheld ic_next 40

make_handheld ic_play_for_notif 32
make_handheld ic_pause 32 ic_pause_for_notif
make_handheld ic_prev 32 ic_prev_for_notif
make_handheld ic_next 32 ic_next_for_notif

make_handheld ic_upper_directory 20

make_handheld ic_search 24
make_handheld ic_play_all 24
make_handheld ic_preference 24

make_handheld ic_shortcut_player 48
make_handheld ic_shortcut_playlist 48

for x in ic_repeat_{one,all,off} ic_shuffle_{on,off}; do
	make_handheld $x 30
done


for ambient in "" "_ambient"; do
	make_wear ic_play${ambient} 50
	make_wear ic_pause${ambient} 50
	make_wear ic_prev${ambient} 40
	make_wear ic_next${ambient} 40

	for x in ic_repeat_{one,all,off} ic_shuffle_{on,off}; do
		make_wear $x${ambient} 30
	done
done

make_wear ic_upper_directory 20

make_wear ic_play_for_notif 32
make_wear ic_pause 32 ic_pause_for_notif
make_wear ic_prev 32 ic_prev_for_notif
make_wear ic_next 32 ic_next_for_notif
